Irraquated/Pokemon-Showdown

tournaments/index.js
Please check my syntax since if I get this wrong its major
=> Allow drivers to start/moderate tours

tournaments/index.js
=> Add /remind

app.js, commands.js, components.js, rooms.js, spamroom.js
This has worked on every server I've used it on, should act as a replacement for shadowban
=> Add spamroom

commands.js
I think kick is unusable by ros cuz of this, PM me with questions
=> Attempt to fix kick

config/custom.css
=> Roomintro CSS

config/custom.css
I basically just added a no-repeat to the image, and took the hexadecimal of the right part of the image and set it as a background color so it would look perfect.
=> Fixed the header, for people with big screens

data/scripts.js
=> Make random lc and random monotype supported tiers

components.js
=> Remove Casino and Transferbucks

config/custom.css
These are some custom broadcast-red, broadcast-green and broadcast-blue.
=> upgraded broadcast-red/green/blue

config/custom.css
I also deleted the roomintro css since you aren't gonna use it, and fixed the indentation of the broadcast css.
=> Teambuilder CSS

components.js
It's a poll for the doubles's room which has only doubles tiers
=> Added /doublespoll

config/custom.css
Made closebutton and minimize button have a darker color so that it wouldn't fade out in the tabbar button cur.
And made them have different hover colors.
=> closebutton and minimizebutton updates

data/rulesets.js
=> Add duo type clause

core.js
You cant just change this without breaking custom symbol. PM me if you don't get it.
=> Fix a shop glitch

config/custom.css
=> Upgraded teambuilder CSS.

config/custom.css
=> Added teambuilder buttons coloring

config/custom.css
you might have noticed that the tabbar button highlight was glitching a bit, well that fixes it.
=> tabbar highlight fix

components.js, gulpfile.js
If the user is already away, it should check the length of the actual
username, not the username plus the status, when checking if the new
status makes the username too long.
=> Fix bug in changing /away status

app.js, chat-plugins/nimbus.js, chat-plugins/trainer-cards.js, command-parser.js, commands.js, components.js, config/commands.js, config/formats.js, core.js, rooms.js, simulator.js, team-validator.js, tools.js, tournaments/index.js, users.js
If you need to use /eval, add your userid to ``exports.consoleips`` in
config/config.js, instead of overwriting
User.prototype.hasSysopAccess().
Run npm test from the command line before making changes so these errors
can be avoided before the fact.
=> Fix npm test errors. refactor, remove SysopAccess

config/custom.css
Some default colors for the links and buttons inside the different broadcast.
=> config.js: broadcast links & buttons

core.js
Change price if you want, no one knew a good price.
=> Add declare as shop item

chat-plugins/poof.js
I dont know why i need that comma but I do
=> Add docG poof

components.js
This has needed some cleanup and organization for some time. In this format, it is easier to read, especially for main staff who want to check on our commands. No command has been edited except for some minor text changes.
Please test before using or get jd to, it works for me but theres a lot I moved around
=> Rework Components.js

config/custom.css
also added some .menugroup .button.disabled coloring.
=> Added bg divs

commands.js
=> Allow leaders to /gdeclare

config/custom.css
I re-arranged  the css to make it less confusing, made a none blue css that looks neutral.
Made a lot of minor fixes, plus the watch a battle fix which was quite the pain in the ass.
That was in total a 3 hour job.
=> custom.css: Watch a battle p1 fix + new teambuilder CSS

config/custom.css
Reverts Irraquated/Pokemon-Showdown#89
=> Revert "custom.css: Watch a battle p1 fix + new teambuilder CSS"

components.js
Since the doubles room was deleted, there's no use for this command anymore, so might as well get rid of it.
=> components.js: deleted /doublespoll

app.js
Reverts Irraquated/Pokemon-Showdown#96
=> Revert "Temp remove spamroom"

config/custom.css
http://prntscr.com/70apsd + http://prntscr.com/70aq60
=> custom.css: tournament css + !dt css

config/custom.css
http://prntscr.com/70y16i + http://prntscr.com/70y374 + http://i.imgur.com/x6FROb9.png?2
=> custom.css: minor tweaks

config/custom.css
before: http://prntscr.com/710ybj
after: http://prntscr.com/710yj8
=> custom.css: watch a battle fix

components.js
regular polls don't fit at all, so that'll go.
=> components.js: a poll for Other Metas

config/custom.css
Made a black statbar which catches a bit more the eye, changes from the boring old one.
before: http://prntscr.com/722hyk
after: http://prntscr.com/722hbz
for the teambuilder
before: http://prntscr.com/722lwo
after: http://prntscr.com/722lro
=> custom.css: statbar tweak + teambuilder additions

components.js
updated the poll so it doesn't show SeasonalSuperStaffBros, but the new OM of the Month.
=> componentsjs: ompoll tweak

chat-plugins/ez-emotes.js
this isnt important and can wait until the next server restart
=> allow regulars to see emoteStatus
